language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t mrc007/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mrc007/docker-react npm run test

# this section is to deploy the travis file in AWS elasticbean stalk 

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-436287192363"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  